[[study]]
a="DCR 2023 Working"
f="8.14.2"
dss="C:/Users/FooBar/Documents/modeling_studies/0/study_0.dss"

[[study]]
a="DCR 2023 Draft"
f="9.0.0"
dss="C:/Users/FooBar/Documents/modeling_studies/1/study_1.dss"

[[study]]
a="DCR 2023 Final"
f="9.2.0"
dss="C:/Users/FooBar/Documents/modeling_studies/2/study_2.dss"
