{% set data = load_file_data(filename='../pyproject.toml', from_recipe_dir=True) %}

package:
  name: blendss
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  script: "python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python
  
requirements:
  host:
    - python
  run:
    - python
    {% for dep in data['project']['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests

about:
  home: https://github.com/centralvalleymodeling/blendss
  summary: Combine multiple DSS files into one for post-processing, and model comparison.
  license: {{ data.get('license') }}
  license_file: LICENSE
